name: Actions Workflow

on:
  # repository_dispatch:
  #   types: [build]

  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  push:
    branches: # to run on all branches except tle listed we can use branches-ignore:
      # branches and branches-ignore are either/or
      - main
      - "feature/*" # matches feature/featA, feature/featB but not feature/feat/new
      - "feature/**" # matches feature/feat/new as well
      - "!feature/featC" # This branch will not be included as the name starts with !
      # Individually ignored branches have to be placed after theincluded branches.
      # Possibly you can use "feature/feat[ABC]" to filter feature/featA, feature/featB and feature/featC.
    tags:
      - "v1.*" # Tags work the same as branches and can use tags-ignore.
    # paths:
    #   - "**.js" # Also individual paths can be targeted and ignored paths-ignore.
    #   - "!filename.js"
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    types: [opened, assigned, closed, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo "${{ github.event.client_payload.env }}"
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GIT_REPOSITORY
          # git checkout $GITHUB_SHA

      - name: checkout
        uses: actions/checkout@v1

      - name: List files again
        run: |
          pwd
          ls -a
          env

      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Tim

      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
