name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # container: node:13.5.0-alpine3.10
    # container:
    #   image: node:13.5.0-alpine3.10
    # steps:
    #   - name: Log node version
    #     run: |
    #       node -v
    #       cat /etc/os-release
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H "Content-Type: application/json" -d "{\"username\": \"hello\",\"address\": \"dwded\"}"'
      - name: Get all users
        run: curl http://localhost:3001/api/user
