name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    environment: test # <--- here
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: echo a string
        run: echo "Hello Tim"
        # continue-on-error: true
      - name: multiline script
        # if: failure() # continue-on-error allows all to continue
        run: |
          node -v
          npm -v

      - name: python command
        shell: python
        run: |
          import platform
          print(platform.processor())

  run-windows-command:
    environment: test # <--- here
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: powershell command
        run: Get-Location

      - name: bash command
        shell: bash
        run: pwd
