name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    environment: test # <--- here
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Tim"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        shell: python
        run: |
          import platform
          print(platform.processor())

  run-windows-command:
    environment: test # <--- here
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: powershell command
        run: Get-Location
      - name: bash command
        shell: bash
        run: pwd
