name: WhatWhen

on:
  check_run:
    branches:
      - '*'
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  pull_request_target:
    branches: 
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: payload
        run: echo "${{ github.event.client_payload.env }}"
    
      - name: Dump github context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: is pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "Pull Request from - ${{ github.head_ref }}"
          echo "Pull request to   - ${{ github.base_ref }}"

      - name: is pull request target
        if: github.event_name == 'pull_request_target'
        run: |
          echo "Pull Request Target from - ${{ github.head_ref }}"
          echo "Pull request Target to   - ${{ github.base_ref }}"
      
      - name: is push
        if: github.event_name == 'push'
        run: echo "Push on ${{ github.ref }}"

