name: WhatWhen

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
  pull_request_target:
    branches: 
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      - name: is pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "Pull Request from - ${{ github.head_ref }}"
          echo "Pull request to   - ${{ github.base_ref }}"

      - name: is pull request target
        if: github.event_name == 'pull_request_target'
        run: |
          echo "Pull Request Target from - ${{ github.head_ref }}"
          echo "Pull request Target to   - ${{ github.base_ref }}"
      
      - name: is push
        if: github.event_name == 'push'
        run: echo "Push on ${{ github.ref }}"

